version: '3.10'

services:
  web:
    container_name: smart-web
    hostname: smart-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: smart-db
    hostname: smart-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: smart
    ports:
      - "6543:5432"
  redis:
    image: redis:7.0